# Use the latest version of postgress.
FROM postgres:latest
# Set environment variables for Postgres user, password, and database.
ENV POSTGRES_USER=${PGUSER}
ENV POSTGRES_PASSWORD=${PGPASSWORD}
ENV POSTGRES_DB=${PGDATABASE}


